# Generated by Django 3.2.7 on 2021-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211012_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
