# Generated by Django 3.2.7 on 2021-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='discont',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
